name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install Dependencies and Run Checks
        run: |
          cd ./frontend/app
          npm install
          yarn prettier --write src
          npx eslint . --fix