name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run Prettier
        run: yarn prettier --write src
      - name: Run ESLint
        run: npx eslint . --fix
